apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  mysql.cnf: |
    [mysqld]
    default-storage-engine=innodb
    innodb_buffer_pool_size=256M
    innodb_log_file_size=64M
    max_connections=100
    key_buffer_size=16M
    thread_cache_size=8
    query_cache_size=16M
    tmp_table_size=32M
    max_heap_table_size=32M