{{- $mysqlPassword := randAlphaNum 32 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ $mysqlPassword | b64enc | quote }}
  MYSQL_DATABASE: {{ "ems_scraper" | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: env-vars
type: Opaque
stringData:
  DATABASE_URL: "mysql://root:{{ $mysqlPassword }}@mysql-service:3306/ems_scraper"
